### ISSUE TITLE
Open multiple files at once, without opening previous tabs

### ISSUE THREAD

**Issue by lofidevops** [RolandPheasant/TailBlazer#166] opened 2016-11-16 07:49 UTC
I am logging multiple applications. Some applications generate multiple logfiles, not necessarily in the same folder. I'd like to launch a separate instance of TailBlazer for each application, with all logfiles for that application in that instance.

A simple solution is to make a Windows shortcut calling `tailblazer.exe C:\path\file1.log C:\path2\file2.log`

This does launch a new instance of TailBlazer, but it includes all tabs from the last instance of TailBlazer. Is it possible to inhibit this behaviour? (I couldn't find docs on command line options.)

**Comment by kwill** [comment] 2016-11-16 07:55
I don't know if this is related to / a duplicate of https://github.com/RolandPheasant/TailBlazer/issues/160

**Comment by RolandPheasant** [comment] 2016-11-16 19:43
There are currently no CommandLine options. but I think adding one to disable loaded previous tabs is a good idea. 

Btw did you know you can drag the tabs out into a new window?

**Comment by kwill** [comment] 2016-11-17 08:18
Personally, I would prefer to not have them there in the first place, but I will try that out. Thanks!

**Comment by Trinition** [comment] 2018-06-19 16:45
I come at this from a different perspective but probably would have the same underlying mechanism: the ability to open multiple log files from the Open dialog.  I, too, have multiple log files for an application that I want opened together.  I'm perfectly fine using the Open dialog, but don't like having to singly select files.

**Closed** 2023-07-04 17:34 UTC
